// <auto-generated />
namespace COVID19TriC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class formatThePhoneNo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(formatThePhoneNo));
        
        string IMigrationMetadata.Id
        {
            get { return "202011272024324_formatThePhoneNo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
