// <auto-generated />
namespace COVID19TriC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class persontabledescriptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(persontabledescriptions));
        
        string IMigrationMetadata.Id
        {
            get { return "202011240059360_person-table-descriptions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
